language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - mvn clean install -Plocal-depl-j2se-hsqldb -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: marcus.maccio@gmail.com